---
- hosts: all
  become: no
  gather_facts: yes
  vars_files:
  - ../variables/node_kernelp.yaml
  tasks: 

  - name: Set {{ item.param }}
    sysctl:
      name={{ item.param }}
      value={{ item.value }}
      state=present
      reload=yes
    with_items: "{{ kernel_parameters }}"