---
- name: Proxmox VE Node Setup
  hosts: all
  gather_facts: true
  become: no
  vars:
    # Linux kernel parameters
    kernel_parameters:
      - { param: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
      - { param: 'net.ipv6.conf.default.disable_ipv6', value: '1' }
    # APT repositories
    add_apt_repositories:
      - 'deb http://ftp.jp.debian.org/debian bookworm main contrib'
      - 'deb http://ftp.jp.debian.org/debian bookworm-updates main contrib'
      - 'deb http://security.debian.org/debian bookworm-security main contrib'
    del_apt_repositories:
      - 'deb http://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise'
    # APT packages
    add_apt_packages:
      - 'hwloc=2.9.0-1'
      #- 'curl'
      #- 'wget'
    del_apt_packages:
      - 'nano'
    # Systemd services
    disable_services:
      - 'ksmtuned.service'
    enable_services:
  roles:
   - common_debian
   - proxmox_nodes