[global]
keyboard = "jp"
country = "jp"
fqdn = "prox3.example.local"
mailto = "mail@example.com"
timezone = "Asia/Tokyo"
root-password = "proxmoxer"
root-ssh-keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0jmOnc6a3vUgk/fVPYvP8oQ8veVRHsYa7wO1trv5X6nPTUuApqglJ4Tbynvan7aQKgJeZWjKehtHwpqkCYg0rfp27wNdmA6xwRaTnLzd8erNr7cqSBAyvLbelkncKCeqpV+pwC6XqGEWL9sEETvaYCCiz1X030U6nhVtuyBSeKPea8cPEET1Umnp3ibtc6o+nLQIXZN4BwXzd+NiMDYjOogWZAgq+kdtuC+EkDJl1R3tl0B/CbKXQQetybHAYrMzTUgpGHNSEx2OMLhte1Bl3OpqTR2OKQwgMkD4KE7WZu7lkDyxjlY9FTT3/1JY2BHNIJPTvLnx7QhYpLXYt64fh root@proxadm1"
]

[network]
source = "from-answer"
cidr = "192.168.56.13/24"
dns = "192.168.56.1"
gateway = "192.168.56.1"
filter.ID_NET_NAME = "enp0s8"

[disk-setup]
filesystem = "ext4"
disk-list = ["sda"]

[first-boot]
source = "from-url"
ordering = "before-network"
url = "http://192.168.56.7/proxmox-answer/first-boot.sh"

